name: Tests

on:
  push:
    branches: [ main, gh-pages ]
  pull_request:
    branches: [ main, gh-pages ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install BATS
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        sudo ./install.sh /usr/local

    - name: Install kcov
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev
        wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
        tar xzf master.tar.gz
        cd kcov-master
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    - name: Run tests with coverage
      run: |
        cd "$GITHUB_WORKSPACE"
        chmod +x test/install.bats
        kcov --coveralls-id=$GITHUB_RUN_ID --exclude-pattern=bats-core,tests coverage test/install.bats

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/coverage.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true 